---
- name: recover backup
  synchronize:
    src: "{{ fworch_home }}/backup_ui/ui"
    dest: "{{ fworch_home }}"
  delegate_to: "{{ inventory_hostname }}"
  listen: "ui handler"
  when: ui_handler_guard == "start"
  become: yes

- name: delete backup
  file:
    state: absent
    path: "{{ fworch_home }}/backup_ui"
  listen: "ui handler"
  become: yes
