---
- name: recover backup
  synchronize:
    src: "{{ fworch_home }}/backup_importer/importer"
    dest: "{{ fworch_home }}"
  delegate_to: "{{ inventory_hostname }}"
  listen: "importer handler"
  when: importer_handler_guard == "start"
  become: yes

- name: delete backup
  file:
    state: absent
    path: "{{ fworch_home }}/backup_importer"
  listen: "importer handler"
  become: yes
  