---
- hosts: all
  roles:
    - iso-common

- hosts: backends
  roles:
    - backend

- hosts: backends
  roles:
    - docker
    - api
  when: run_on_github is not defined
  # docker does not work on github out of the box

- hosts: frontends
  roles:
    - frontend

- hosts: importers
  roles:
    - importer

- hosts: authservers
  roles:
    - auth_backend
    - auth_frontend

- hosts: sampleservers
  roles:
    - import-samples
