---
- hosts: all
  roles:
    - iso-common

- hosts: backends
  roles:
    - docker
    - backend
    - api

- hosts: frontends
  roles:
    - frontend

- hosts: importers
  roles:
    - importer

- hosts: authservers
  roles:
    - auth_backend
    - auth_frontend

- hosts: sampleservers
  roles:
    - import-samples
