---
- hosts: all
  roles:
    - iso-common

- hosts: backends
  roles:
    - { role: docker, when: "run_on_github is not defined" }
    - backend
    - { role: api, when: "run_on_github is not defined" }
   # todo: make api (and docker) work with github actions
    - auth

- hosts: frontends
  roles:
#    - { role: frontend, when: "ui is not defined or (ui is defined and (ui == 'old' or ui == 'both'))"}
    - { role: frontend, when: "ui is defined and ui == 'old'"}
#    - { role: frontend-new, when: "ui is not defined or (ui is defined and (ui == 'new' or ui == 'both'))"}
    - { role: frontend-new, when: "ui is not defined or ui == 'new'"}

- hosts: importers
  roles:
    - importer

- hosts: sampleservers
  roles:
    - { role: sample-data, when: "without_sample_data is not defined" }
    - { role: sample-data-connect-sting, when: "connect_sting is defined" }
