---
- hosts: all
  roles:
    - common
  tags:
    - backend

- hosts: backendserver
  roles:
    - database
  tags:
    - backend

- hosts: authserver
  roles:
    - openldap-server
    - lib
    - auth
  tags:
    - backend

- hosts: apiserver
  roles:
    - { role: docker, when: "run_on_github is not defined" }
    - { role: api, when: "run_on_github is not defined" }
  tags:
    - backend
   # todo: make api (and docker) work with github actions

# restart authserver now that the API is ready.
- hosts: authserver
  tasks:
    - name: restart auth service
      command: "systemctl restart {{ auth_service_name }}"
      become: yes
  tags:
    - backend

- hosts: frontends
  roles:
    - { role: lib, when: "'authserver' not in {{ group_names }}"}
    - frontend
    - { role: frontend-php, when: "ui_php is defined"}
  tags:
    - frontend

- hosts: importers
  roles:
    - importer
  tags:
    - frontend

- hosts: sampleserver
  roles:
    - { role: sample-data, when: "without_sample_data is not defined" }
    - { role: sample-data-connect-sting, when: "connect_sting is defined" }
  tags:
    - samples
    - backend

- hosts: authserver
  roles:
    - { role: sample-auth-data, when: "without_sample_data is not defined" }
  tags:
    - samples
    - backend
  # todo: add a meta dependency on role sample-data

# restart importer to make sure it works correctly with sample data
- hosts: importers
  tasks:
    - name: restart importer service
      command: "/etc/init.d/fworch-importer restart"
      become: yes
  tags:
    - backend

# simply set new version in config file
- hosts: all
  roles:
    - upgrade-completion
  tags:
    - backend
    - frontend

- hosts: all
  roles:
    - test
  tags:
    - test
