---
- hosts: all
  roles:
    - iso-common

- hosts: backends
  roles:
    - backend
    - docker_from_pip
    - api

- hosts: frontends
  roles:
    - frontend

- hosts: importers
  roles:
    - importer

- hosts: authservers
  roles:
    - auth_backend
    - auth_frontend

- hosts: sampleservers
  roles:
    - import-samples
