---
- hosts: all
  roles:
    - iso-common

- hosts: backends
  roles:
    - database
    - auth
    - openldap-server

- hosts: apiservers
  roles:
    - { role: docker, when: "run_on_github is not defined" }
    - { role: api, when: "run_on_github is not defined" }
   # todo: make api (and docker) work with github actions

- hosts: frontends
  roles:
    - frontend
    - { role: frontend-php, when: "ui_php is defined"}
#    - { role: frontend-new, when: "ui is not defined or ui == 'new'"}

- hosts: importers
  roles:
    - importer

- hosts: sampleservers
  roles:
    - { role: sample-data, when: "without_sample_data is not defined" }
    - { role: sample-data-connect-sting, when: "connect_sting is defined" }
