---
# common
- hosts: isosrv
  roles:
    - iso-common

# backend
- hosts: isosrv
  roles:
    - backend
    - docker
    - api

# frontend
- hosts: isosrv
  roles:
    - frontend

# importer
- hosts: isosrv
  roles:
    - importer

# auth
- hosts: isosrv
  roles:
    - auth_backend
    - auth_frontend

# iso-samples
- hosts: isosrv
  roles:
    - import-samples
