---
- hosts: all
  roles:
    - iso-common

- hosts: backends
  roles:
    - { role: docker, when: "run_on_github is not defined" }
    - backend
    - { role: api, when: "run_on_github is not defined" }
   # todo: make api (and docker) work with github actions
    - auth_backend

- hosts: frontends
  roles:
    - frontend
    - auth_frontend

- hosts: importers
  roles:
    - importer

- hosts: sampleservers
  roles:
    - sample-data
