---
- hosts: all
  roles:
    - iso-common

- hosts: backends
  roles:
    - { role: docker, when: "run_on_github is not defined" }
    - backend
    - { role: api, when: "run_on_github is not defined" }
   # todo: make api (and docker) work with github actions
    - auth_backend

- hosts: frontends
  roles:
    - { role: frontend, when: "ui is not defined or (ui is defined and (ui == 'old' or ui == 'both'))"}
    - auth_frontend
    - { role: frontend-new, when: "ui is not defined or (ui is defined and (ui == 'new' or ui == 'both'))"}

- hosts: importers
  roles:
    - importer

- hosts: sampleservers
  roles:
    - sample-data
    - { role: sample-data-connect-sting, when: "connect_sting is defined" }
