---

# todo: add switch "demo_install" to disable all invasive actions like change pwd, delete devices, ... 

- hosts: all
  roles:
    - common

- hosts: backendserver
  roles:
    - database

- hosts: authserver
  roles:
    - openldap-server
    - lib
    - auth

- hosts: apiserver
  roles:
    - { role: docker, when: "run_on_github is not defined" }
    - { role: api, when: "run_on_github is not defined" }
   # todo: make api (and docker) work with github actions

- hosts: frontends
  roles:
    - lib
    - frontend
    - { role: frontend-php, when: "ui_php is defined"}

- hosts: importers
  roles:
    - importer

- hosts: sampleserver
  roles:
    - { role: sample-data, when: "without_sample_data is not defined" }
    - { role: sample-data-connect-sting, when: "connect_sting is defined" }

- hosts: authserver
  roles:
    - { role: sample-auth-data, when: "without_sample_data is not defined" }
  # todo: add meta dependency on role sample-data

- hosts: all
  roles:
    - { role: test, when: "test is defined" }
