- block:
    - set_fact: ansible_user_home="{{ lookup('env','HOME') }}"

    - name: add user sampledev
      user:
        name: "{{ sample_config_user }}"
        comment: ITSecurity Organizer Import User for sample configs
        uid: 60321
        home: "{{ sample_config_user_home }}"
        shell: /bin/bash
        group: itsecorg
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: ".ssh/id_rsa.{{ sample_config_user }}"
            
    - name: add sample-data user pub key to its authorized_keys
      shell: "cat {{ sample_config_user_home }}/.ssh/id_rsa.{{ sample_config_user }}.pub >> {{ sample_config_user_home }}/.ssh/authorized_keys"
        
    - name: correct sample-data users authorized_keys file acls
      file: 
         path: "{{ sample_config_user_home }}/.ssh/authorized_keys"
         owner: "{{ sample_config_user }}"
         mode: 0600

    - name: fetch sample-data user pub key
      fetch:
        src: "{{ sample_config_user_home }}/.ssh/id_rsa.{{ sample_config_user }}.pub"
        dest: "/tmp/"

    - name: fetch sample-data user priv key
      fetch:
        src: "{{ sample_config_user_home }}/.ssh/id_rsa.{{ sample_config_user }}"
        dest: "/tmp/"

    - name: copy sample configs
      copy:
        src: "sample-configs"
        dest: "{{ sample_config_user_home }}"
        owner: "{{ sample_config_user }}"
        group: itsecorg

    - name: copy config changes scripts
      copy:
        src: "config_changes"
        dest: "{{ sample_config_user_home }}"
        owner: "{{ sample_config_user }}"
        group: itsecorg

    - name: Creates a cron file under /etc/cron.d
      cron:
        name: change fw config
        weekday: "*"
        minute: "*"
        hour: "*"
        user: "{{ sample_config_user }}"
        job: "python3 {{ sample_config_user_home }}/write_date_to_comment.py {{ sample_config_user_home }}/enlarge_rule.py"
        cron_file: ansible_FWOrch_change_config_comment
  become: yes
