# create query collection for basic tasks fworch_basics
# via direct hasura DB access

- name: copy query files to target
  copy:
    src: "query-collections"
    dest: "{{ api_home }}/"
    mode: 0644
  become: yes

- name: copy template for query sql code
  template:
    src: "api-set-all-queries.sql.j2"
    dest: "{{ api_home }}/query-collections/api-set-all-queries.sql"
    mode: 0644
  become: yes

- block:
    - name: remove all collections from allowlist and delete them opening up the db
      command: 'psql -h {{ fworch_db_host }} -U {{ fworch_dbadmin_name }} -d {{ fworch_db_name }} -c "DELETE FROM hdb_catalog.hdb_allowlist; DELETE FROM hdb_catalog.hdb_query_collection;"'

    - name: create .pgpass file
      lineinfile:
        path: "{{ fworch_home }}/.pgpass"
        create: yes
        mode: 0600
        line: "{{ fworch_db_host }}:{{ fworch_db_port }}:{{ fworch_db_name }}:{{ fworch_dbadmin_name }}:{{ dbadmin_pwd }}"

    - name: insert query collection
      command: 'psql -h {{ fworch_db_host }} -U {{ fworch_dbadmin_name }} -d {{ fworch_db_name }} -c "\i {{ api_home }}/query-collections/api-set-all-queries.sql"'

    - name: add collections to allowlist
      command: 'psql -h {{ fworch_db_host }} -U {{ fworch_dbadmin_name }} -d {{ fworch_db_name }} -c "\i {{ api_home }}/query-collections/api-add-query-collections-to-allowlist.sql"'

    - name: clean up .pgpass file
      file:
        path: "{{ fworch_home }}/.pgpass"
        state: absent

  become: yes
  become_user: "{{ fworch_user }}"
