# create query collection for basic tasks fworch_basics via direct hasura DB access

- set_fact:
    query_collection_dict:
      - basic:
        collection_name: basic
        collection_comment: "basic queries"
        query_json_file: "api-queries-report-basic-squashed.json"
      - filters:
        collection_name: filters
        collection_comment: "filter queries"
        query_json_file: "api-queries-report-filters-squashed.json"
      - rule:
        collection_name: rule
        collection_comment: "rule queries"
        query_json_file: "api-queries-report-rule-squashed.json"

- name: copy query files to target
  copy:
    src: "query-collections"
    dest: "{{ api_home }}/"
    owner: "{{ fworch_user }}"
    group: "{{ fworch_user }}"
  become: yes

- name: create sql command files from template for adding query collections
  template:
    src: "api-set-queries.sql.j2"
    dest: "{{ api_home }}/query-collections/reporting/api-set-queries-{{ item.collection_name }}.sql"
    mode: 0644
    owner: "{{ fworch_user }}"
    group: "{{ fworch_user }}"
  become: yes
  loop: "{{ query_collection_dict }}"

- block:
    - name: create .pgpass file
      lineinfile:
        path: "{{ fworch_home }}/.pgpass"
        create: yes
        mode: 0600
        line: "{{ fworch_db_host }}:{{ fworch_db_port }}:{{ fworch_db_name }}:{{ fworch_dbadmin_name }}:{{ dbadmin_pwd }}"

    - name: removeline breaks and multiple consecutive spaces from json files
      shell: "cat api-queries-report-{{ item.collection_name }}.json | tr -s '[:space:]' | tr -d '\n' > {{ item.query_json_file }}"
      args:
        chdir: "{{ api_home }}/query-collections/reporting"
        creates: "{{ api_home }}/query-collections/reporting/{{ item.query_json_file }}"
      loop: "{{ query_collection_dict }}"
      register: tr_result
      # todo: error handling

    - name: execute sql command files for adding query collections
      command: 'psql -h {{ fworch_db_host }} -U {{ fworch_dbadmin_name }} -d {{ fworch_db_name }} -c "\i {{ api_home }}/query-collections/reporting/api-set-queries-{{ item.collection_name }}.sql"'
      loop: "{{ query_collection_dict }}"
      register: sql_result
      # todo: error handling

    - name: clean up .pgpass file
      file:
        path: "{{ fworch_home }}/.pgpass"
        state: absent

  become: yes
  become_user: "{{ fworch_user }}"
