# create query collection for basic tasks fworch_basics

- set_fact: api_url_queries="https://{{ ansible_hostname }}:{{ api_web_port }}/api/v1/query"

- name: create basic queries
  uri:
    url: "{{ api_url_queries }}"
    method: POST
    headers:
      Content-Type: "application/json"
      x-hasura-admin-secret: "st8chelt1er"
      x-hasura-role: "admin"
    body_format: json
    src: api-queries-basic.json
    validate_certs: no

# - name: add basic query collection to allow-list
#   shell: "sleep 1"

# create query collection for reporting fworch_reporting

# - name: create reporting queries
#   uri:
#     url: "{{ api_url_queries }}"
#     method: POST
#     src: api-queries-reporting.graphql

# - name: add basic query collection to allow-list
#   shell: "sleep 1"
