---
- block:  
   - set_fact: api_home="{{ iso_home }}/api"

   - name: create extension pgcrypto for jwt auth
     shell: 'psql -c "DO \$do\$ BEGIN IF NOT EXISTS (SELECT * FROM pg_extension WHERE extname = ''pgcrypto'') THEN CREATE EXTENSION pgcrypto; END IF; END \$do\$"'

   - name: create pgtap for running unit tests on database 
     shell: 'psql -c "DO \$do\$ BEGIN IF NOT EXISTS (SELECT * FROM pg_extension WHERE extname = ''pgtap'') THEN CREATE EXTENSION pgtap; END IF; END \$do\$"'

  become: yes
  become_user: postgres
