
- name: set grants hasura schema from ansible 2.10
  community.postgresql.postgresql_query:
    db: "{{ fworch_db_name }}"
    query: "GRANT USAGE ON SCHEMA {{ item }} TO dbbackupusers; Grant select on ALL TABLES in SCHEMA {{ item }} to group dbbackupusers; ALTER DEFAULT PRIVILEGES IN SCHEMA {{ item }} GRANT SELECT ON TABLES TO group dbbackupusers;"
    as_single_query: "{{ postgresql_query_as_single_query }}"
  become: true
  become_user: postgres
  loop:
    - hdb_catalog
  become: true
  become_user: postgres
  