- block:  
   - set_fact: api_home="{{ fworch_home }}/api"

   - name: generate jwt secret
     shell: "< /dev/urandom tr -dc a-f0-9 | head -c${1:-64}"
     register: jwt_secret

   - set_fact: api_hasura_jwt_secret="{{ jwt_secret.stdout }}"
  
   - name: remove api home
     file:
        path: "{{ api_home }}"
        state: absent

   - name: create api home
     file:
        path: "{{ api_home }}"
        state: directory
        mode: "0755"
        owner: "{{ fworch_user }}"
        group: "{{ fworch_user }}"

   - name: make sure secrets dir exists
     file:
        path: "{{ fworch_home }}/etc/secrets"
        state: directory
        mode: "0700"
        owner: "{{ fworch_user }}"
        group: "{{ fworch_user }}"

   - name: write api_hasura_jwt_secret into file for reference
     lineinfile:
        path: "{{ fworch_home }}/etc/secrets/jwt_private.key"
        line: "{{ jwt_secret.stdout }}"
        create: yes
        mode: "0600"
        owner: "{{ fworch_user }}"
        group: "{{ fworch_user }}"

   - name: add user {{ fworch_user }} to group docker
     user: name={{ fworch_user }}
           groups=docker
           append=yes

  become: yes
