
# this playbook sets up the api

- name: hasura basic file setup 
  import_tasks: hasura-files.yml

- name: hasura install 
  import_tasks: hasura-install.yml

- name: hasura basic config
  import_tasks: hasura-basic-config.yml

- name: create query_collections and add to allow-list 
  import_tasks: api-query-collection.yml

- name: api create documentation
  import_tasks: hasura-create-docu.yml
  when: "api_docu is defined and api_docu == 'yes'"
