---
- block:  
   - set_fact: api_home="{{ iso_home }}/api"
   - set_fact: hasura_bin="/usr/local/bin/hasura"

   - name: remove api home
     file:
        path: "{{ api_home }}"
        state: absent
   
   - name: create api home
     file:
        path: "{{ api_home }}"
        state: directory
        mode: 0755
        owner: "{{ iso_user }}"
   
   - name: copy hasura docker-run script
     template:
       src: docker-run.sh.j2
       dest: "{{ api_home }}/docker-run.sh"
       backup: yes
       mode: 0755
       owner: "{{ iso_user }}"
       
   - name: add user {{ iso_user }} to group docker  
     user: name={{ iso_user }}
           groups=docker
           append=yes
  become: yes

- name: execute hasura docker-run
  shell: "cd {{ api_home }}; {{ api_home }}/docker-run.sh"
  become: yes
  become_user: "{{ iso_user }}"
   
- block:  
   - name: download hasura cli installer
     get_url:
        url: https://github.com/hasura/graphql-engine/raw/master/cli/get.sh
        dest: "{{ api_home }}"
        mode: 0755
     environment: "{{ proxy_env }}"
   
   - name: execute hasura cli installer
     shell: "{{ api_home }}/get.sh"
     become: yes
     environment: "{{ proxy_env }}"
   
   - name: initialize hasura cli directory
     shell: "cd {{ api_home }} && {{ hasura_bin }} init --directory itsecorg --endpoint http://{{ api_hostname }}:{{ api_port }} --admin-secret {{ api_hasura_admin_secret }}"
     become: yes
   
   - name: copy hasura metadata to cli directory
     copy:
       src: hasura_metadata.yaml
       dest: "{{ api_home }}/itsecorg/migrations/metadata.yaml"
       backup: yes
       mode: 0644
       owner: "{{ iso_user }}"
   
   - name: import hasura metadata
     shell: "cd {{ api_home }}/itsecorg && {{ hasura_bin }} metadata apply --from-file"
     
   - name: copy hasura docker systemd service script
     template:
       src: hasura-docker-api.service.j2
       dest: "/lib/systemd/system/hasura-docker-api.service"
       backup: yes
       mode: 0644
       owner: "root"

   - name: make hasura docker container run at host startup
     command: "systemctl enable hasura-docker-api"
     
  become: yes