# this playbook sets up the api

- name: install apache2
  import_tasks: api-apache-install-and-setup.yml

- name: remove api home
  file:
    path: "{{ api_home }}"
    state: absent

- name: create api home
  file:
    path: "{{ api_home }}"
    state: directory
    mode: "0755"
    owner: "{{ fworch_user }}"
    group: "{{ fworch_user }}"

- name: hasura jwt creation
  import_tasks: hasura-jwt.yml

- name: hasura install 
  import_tasks: hasura-install.yml

- name: hasura basic config
  import_tasks: hasura-basic-config.yml

- name: create query_collections and add to allow-list 
  import_tasks: api-query-collection.yml

- name: api create documentation
  import_tasks: api-create-docu.yml
  when: "api_docu is defined and api_docu == 'yes'"
