- block:
     - name: Install packages for api
       apt:
         name: "{{ packages }}"
       vars:
           packages:
           - python3-flask
           - python3-flask-restful
           - python3-flask-sqlalchemy
           - python3-psycopg2

     - name: create sbin dir
       file:
         path: "{{ iso_home }}/sbin"
         state: directory
         mode: 0755
         owner: itsecorg
         group: itsecorg

     - name: copy api server template
       template:
         src: templates/iso_api_flask_server.py.j2
         dest: "{{ iso_home }}/sbin/iso_api_flask_server.py"

     - name: copy api systemd script
       copy:
        src: iso_api.service
        dest: /lib/systemd/system/
        mode: 0644
        owner: root
        
     - name: make api start at boot
       command: "systemctl enable iso_api"

     - name: start api server
       command: "systemctl start iso_api"

  become: yes

# now in non-root context:            
#- import_tasks: iso-setup-database-as-postgres-user.yml
