all:
  hosts:
    fworch-srv:
      ansible_connection: local
      ansible_host: localhost
    ui-srv:
      ansible_connection: ssh
      ansible_host: 192.168.121.2
  children:
    frontends:
      hosts:
        ui-srv:
    backendserver:
      hosts:
        fworch-srv:
    databaseserver:
      hosts:
        fworch-srv:
    apiserver:
      hosts:
        fworch-srv:
    importers:
      hosts:
        fworch-srv:
    middlewareserver:
      hosts:
        fworch-srv:
    sampleserver:
      hosts:
        fworch-srv:
    testservers:
      hosts:
        fworch-srv:
