# 1. ssh-keygen -t rsa
# Press enter for each line 
# 2. cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
# 3. chmod og-wx ~/.ssh/authorized_keys
# 4. change ansible_connection to ssh and ansible_host to your host

all:
  hosts:
    install-srv:
      ip_address: 127.0.0.1
      ansible_connection: local
      # ansible_connection: local
      # ansible_host: localhost
#   Add servers for distributed installation here. Use these servers in the children dictionary below.
#    ui-srv:
#      ansible_connection: ssh
#      ansible_host: 192.168.121.2
  children:

    frontends:
      hosts:
        install-srv:

    # only one databaseserver should exist
    databaseserver:
      hosts:
        install-srv:

    # only one apiserver should exist
    apiserver:
      hosts:
        install-srv:

    importers:
      hosts:
        install-srv:

    # only one middlewareserver should exist
    middlewareserver:
      hosts:
        install-srv:

    # only one sampleserver should exist
    sampleserver:
      hosts:
        install-srv:

    testservers:
      hosts:
        install-srv:

    # only one logserver should exist
    logserver:
      hosts:
        install-srv:
