
- name: change value for middleware_change_local_ldap if ldap conn already exists to prevent re-creation errors
  set_fact:
    middleware_change_local_ldap: "no"
  when: ldap_conn_present.query_result.0.count >= 1

- name: set add mode for creating ldap tree
  set_fact:
    ldif_changetype: add

- name: copy the ldif templates to system
  template:
    src: "{{ item }}"
    dest: "{{  middleware_ldif_dir }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
    force: yes
  with_fileglob:
    - ../templates/ldif_files/*.j2
  become: yes

- name: add tree
  command: "ldapmodify -H {{ openldap_url }} -D {{ openldap_superuser_dn }} -w {{ ldap_manager_pwd }} -x -f {{  middleware_ldif_dir }}/tree_{{ item }}.ldif"
  loop:
    - level_0
    - level_1
    - level_2
    - systemusers
    - roles
    - tenant0
    - operators
  when: installation_mode == "new"
  # ignore errors only when re-installing on a system
