
  # install all upgrades between running version and version currently being installed

- name: create upgrade dir
  file:
    path: "{{ fworch_home }}/middleware/upgrade"
    state: directory
  become: yes
 
- set_fact: 
    installed_version: "{{ old_version }}"
    current_version: "{{ product_version }}"
    all_upgrades_available: "{{ lookup('fileglob', 'upgrade/*.ldif') }}"
    upgrade_files: []

- name: set list of relevant upgrade files (without extension)
  set_fact:
    upgrade_files: "{{ upgrade_files + [ item | basename | splitext | first | regex_replace('([\\d\\.]+)\\.ldif', '\\1') ] }}"
  when: |
    installed_version < item | basename | splitext | first | regex_replace('([\\d\\.]+)\\.ldif', '\\1')
    and
    current_version >= item | basename | splitext | first | regex_replace('([\\d\\.]+)\\.ldif', '\\1')
  with_fileglob:
    - "../templates/upgrade/*.ldif"

- name: copy the upgrade ldif templates to target
  template:
    src: "../templates/upgrade/{{ item }}.ldif"
    dest: "{{ fworch_home }}/middleware/upgrade/"
  loop: "{{ upgrade_files }}"
  become: yes

- name: install ldap upgrades   
  command: "ldapmodify -H {{ openldap_url }} -D {{ openldap_superuser_dn }} -w {{ ldap_manager_pwd }} -x -f {{ fworch_home }}/middleware/upgrade/{{ item }}.ldif"
  loop: "{{ upgrade_files | sort }}"
