
- name: set grants for schemas before ansible 2.10
  postgresql_query:
    db: "{{ fworch_db_name }}"
    query: "GRANT USAGE ON SCHEMA {{ item }} TO dbbackupusers; Grant select on ALL TABLES in SCHEMA {{ item }} to group dbbackupusers; ALTER DEFAULT PRIVILEGES IN SCHEMA {{ item }} GRANT SELECT ON TABLES TO group dbbackupusers;"
  become: true
  become_user: postgres
  loop:
    - public
    - hdb_catalog
    - request
