---
- name: middleware handler
  ansible.posix.synchronize:
    src: "{{ fworch_home }}/backup_middleware/middleware"
    dest: "{{ fworch_home }}"
  delegate: middleware
  when: middleware_handler_guard == "start"
  become: yes
