---
- name: check for mw backup dir
  stat:
    path: "{{ fworch_home }}/backup_middleware/middleware"
  register: mw_backup_dir_check

- name: recover backup
  synchronize:
    src: "{{ fworch_home }}/backup_middleware/middleware"
    dest: "{{ fworch_home }}"
  delegate_to: "{{ inventory_hostname }}"
  listen: "middleware handler"
  when: mw_backup_dir_check.stat.exists and middleware_handler_guard == "start"
  become: yes

- name: delete backup
  file:
    state: absent
    path: "{{ fworch_home }}/backup_middleware"
  listen: "middleware handler"
  become: yes
  when: mw_backup_dir_check.stat.exists
  
- name: fail message
  debug:
    msg:
    - "An error occured during the upgrade of role {{ role_name }}"
    - "Please restart the server {{ inventory_hostname }}"
    - "Try to upgrade {{ product_name }} later or contact the support support@cactus.de"
  listen: "middleware handler"
  when: middleware_handler_guard == "start"
