
- block:
    - name: Install webserver packages
      package: name={{ item }} state=present
      with_items:
        - "{{ ui_web_server_name }}"

    - name: copy iso httpd config file to apache target
      template:
        src: "httpd.conf"
        dest: "{{ ui_http_conf_dir }}/{{ product_name }}.conf"
        owner: root
        group: root
        
    - name: enable apache modules proxy proxy_http ssl
      command: "a2enmod proxy proxy_http ssl rewrite proxy_wstunnel"

    - name: copy cert creation script to apache target
      script: "apache_create_server_cert.sh" 

    - name: enable itsecorg web site
      shell: "a2ensite {{ product_name }}"

    - name: increase apache timeout to 900 seconds
      lineinfile:
        path: /etc/apache2/apache2.conf
        line: "Timeout 900"

    - name: restart apache
      service:
       name: "{{ ui_web_server_name }}"
       state: restarted     

  become: yes
  environment: "{{ proxy_env }}"
