openldap_server_pkgs:
  - slapd
  - ldap-utils
  - openssl

openldap_server_app_path: "/etc/ldap/"
openldap_server_instance_path: "{{ openldap_server_app_path }}{{ openldap_server_domain_name }}/"
openldap_server_user: "openldap"
