- block: 
     - name: Reload service systemctl
       command: "systemctl daemon-reload"
       listen: "restart daemons"
  
     - name: restart service docker
       service:
         name: docker
         state: restarted
       listen: "restart docker service"
  become: yes
  
  