
- name: removing old legacy importer without legacy name
  ansible.builtin.systemd:
    name: "{{ product_name }}-importer"
    state: stopped
    enabled: no
    daemon_reload: yes
  become: yes
  when: "'importers' in group_names"

- name: remove old importer service file
  file:
    state: absent
    name: "/lib/systemd/system/{{ product_name }}-importer.service"
