---
- name: copy ldif file to system
  template:
    src: second_db.ldif.j2
    dest: /tmp

- name: enhance ldap with ldif files
  command: "ldapmodify -H {{ openldap_url }} -D {{ openldap_superuser_dn }} -w {{ ldap_manager_pwd }} -x -f /tmp/{{ item }}.ldif"
  loop:
    - second_db