---
- name: create sample ldap database directory
  file:
    path: "/var/lib/ldap/{{ sample_ldap_domain_name }}/"
    state: directory
    owner: "{{ openldap_server_user }}"
    group: "{{ openldap_server_user }}"
  become: yes

- name: Create the DB_CONFIG file
  copy:
    src: DB_CONFIG
    dest: /var/lib/ldap/{{ sample_ldap_domain_name }}/DB_CONFIG
    owner: "{{ openldap_server_user }}"
    group: "{{ openldap_server_user }}"
  become: yes

- name: copy the ldif templates to system
  template:
    src: "{{ item }}"
    dest: "/tmp/{{ item | basename | regex_replace('\\.j2$', '') }}"
  with_fileglob:
    - ../templates/*.j2
  become: yes

- name: enhance ldap with ldif files
  command: "ldapmodify -H {{ openldap_url }} -D cn=config -w {{ ldap_manager_pwd }} -x -f /tmp/{{ item }}.ldif"
  loop:
    - second_db
    - ext_role
    - ext_user
    - ext_roles
    - ext_add_user
