# this playbook sets up some sample devices with configs to play around with
# to be executed on the backend server (aka localhost) only which will work as demo data ssh server
  
- name: read ssh_priv_key into var
  slurp:
    src: "{{ sample_config_user_home }}/.ssh/id_rsa.{{ sample_config_user }}"
  register: sample_ssh_priv_key_dict
  become: yes

- block:
    - set_fact: importer_hostname="{{ ansible_hostname }}"          #  TODO: this only works for importer = backend
    # - set_fact: ssh_private_key_sample_server="{{ lookup('file', '/tmp/{{ sample_config_hostname }}/{{ sample_config_user_home }}/.ssh/id_rsa.{{ sample_config_user }}') }}"
 
     # create sample devices and managements in fworchdb: 
    - name: create .pgpass file
      lineinfile:
        path: "{{ fworch_home }}/.pgpass"
        create: yes
        mode: "0600"
        line: "{{ fworch_db_host }}:{{ fworch_db_port }}:{{ fworch_db_name }}:{{ fworch_dbadmin_name }}:{{ dbadmin_pwd }}"

    - name: decode key
      set_fact:
        sample_ssh_priv_key: "{{ sample_ssh_priv_key_dict['content'] | b64decode }}"

    - name: insert test fortinet management
      command: 'psql -h {{ fworch_db_host }} -U {{ fworch_dbadmin_name }} -d {{ fworch_db_name }} -c "DO $do$ BEGIN IF NOT EXISTS (SELECT * FROM management WHERE mgm_name=''fortigate-test'') THEN insert into management (dev_typ_id,mgm_name,ssh_private_key,ssh_public_key,ssh_hostname,ssh_user,do_not_import,config_path,importer_hostname) VALUES (10,''fortigate-test'',''{{ sample_ssh_priv_key }}'','''',''{{ import_sample_server }}'',''{{ sample_config_user }}'',false, ''sample-configs/fortinet_demo/'',''{{ importer_hostname }}'');  END IF; END $do$"'
      #command: 'psql -h {{ fworch_db_host }} -U {{ fworch_dbadmin_name }} -d {{ fworch_db_name }} -c "DO $do$ BEGIN IF NOT EXISTS (SELECT * FROM management WHERE mgm_id=1) THEN insert into management (mgm_id,dev_typ_id,mgm_name,ssh_private_key,ssh_public_key,ssh_hostname,ssh_user,do_not_import,config_path,importer_hostname) VALUES (1,10,''fortigate-test'',''{{ sample_ssh_priv_key }}'','''',''{{ import_sample_server }}'',''{{ sample_config_user }}'',false, ''sample-configs/fortinet_demo/'',''{{ importer_hostname }}'');  END IF; END $do$"'
      
    - name: insert test fortinet gateway
      command: 'psql -h {{ fworch_db_host }} -U {{ fworch_dbadmin_name }} -d {{ fworch_db_name }} -c "DO $do$ BEGIN IF NOT EXISTS (SELECT * FROM device WHERE dev_name=''fortigate-test'') THEN insert into device (mgm_id,dev_name,dev_rulebase,dev_typ_id) VALUES ((select mgm_id from management where mgm_name=''fortigate-test''),''fortigate-test'',''fortigate-test'',10); END IF; END $do$"'

    - name: insert test check point management
      command: 'psql -h {{ fworch_db_host }} -U {{ fworch_dbadmin_name }} -d {{ fworch_db_name }} -c "DO $do$ BEGIN IF NOT EXISTS (SELECT * FROM management WHERE mgm_id=2) THEN insert into management (mgm_id,dev_typ_id,mgm_name,ssh_private_key,ssh_public_key,ssh_hostname,ssh_user,do_not_import,config_path,importer_hostname) VALUES (2,7,''checkpoint-demo'',''{{ sample_ssh_priv_key }}'','''',''{{ import_sample_server }}'',''{{ sample_config_user }}'',false, ''sample-configs/checkpoint_demo/'',''{{ importer_hostname }}''); END IF; END $do$"'
      
    - name: insert test fortinet device for import
      command: 'psql -h {{ fworch_db_host }} -U {{ fworch_dbadmin_name }} -d {{ fworch_db_name }} -c "DO $do$ BEGIN IF NOT EXISTS (SELECT * FROM device WHERE dev_id=2) THEN insert into device (dev_id,mgm_id,dev_name,dev_rulebase,dev_typ_id) VALUES (2,2,''checkpoint-demo'',''IsoAAAA'',7); END IF; END $do$"'

    - name: scan localhost ssh keys
      shell: "ssh-keyscan -H 127.0.0.1 >> ~/.ssh/known_hosts"

    - name: clean up .pgpass file
      file:
        path: "{{ fworch_home }}/.pgpass"
        state: absent

  become: yes
  become_user: "{{ fworch_user }}"
