# this playbook sets up some sample devices with configs to play around with

- block:
    - import_tasks: iso-setup-import-samples-prepare.yml
  become: yes

- block:
    - import_tasks: iso-setup-import-samples.yml
  become: no

- block:
  - name: add auth test data
    include_tasks: auth_test_data.yml
  become: yes
  become_user: postgres
