# this playbook sets up some sample devices with configs to play around with

- name: create import sample user and copy configs
  include_tasks: setup-sample-import.yml
  when: "installation_mode=='new' or sample_role_purpose is match('test')"

- name: install package postgresql-client for adding sample devices to db
  package:
    name: postgresql-client
    state: present
  become: yes

- name: add localhost hostkey to known_hosts
  known_hosts:
    name: localhost
    key: "{{ lookup('pipe', 'ssh-keyscan localhost') }}"
  become: yes
  become_user: "{{ fworch_user }}"

- name: create sample devices in database
  import_tasks: create-devices.yml
  when: "installation_mode=='new' or sample_role_purpose is match('test')"

#todo: above we are adding localhost keys to known_hosts, here again but hashed. Both necessary?
- name: scan localhost ssh keys
  known_hosts:
    name: 127.0.0.1
    key: "{{ lookup('pipe', 'ssh-keyscan -H 127.0.0.1') }}"
  become: yes
  become_user: "{{ fworch_user }}" 

- name: establish cron job to simulate hourly changes to configs
  import_tasks: setup-config-changes.yml
  when: sample_role_purpose is not match('test')
  when: "installation_mode=='new'"

- name: add second ldap database
  import_tasks: add_second_ldap_db.yml
  when: (second_ldap_db | bool) and (sample_role_purpose is not match('test'))
