- block:
    - name: add user sampledev
      user:
        name: "{{ sample_config_user }}"
        comment: fworch import user for sample configs
        uid: 60321
        home: "{{ sample_config_user_home }}"
        shell: /bin/bash
        group: "{{ fworch_user }}"
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: "{{ sample_config_user_home }}/.ssh/id_rsa.{{ sample_config_user }}"

    - name: create file authorized_keys if not existing
      file:
        path: "{{ sample_config_user_home }}/.ssh/authorized_keys"
        state: touch

    - name: add sample-data user pub key to its authorized_keys
      blockinfile:
        path: "{{ sample_config_user_home }}/.ssh/authorized_keys"
        marker: ""
        block: "{{ lookup('file', {{ sample_config_user_home }}/.ssh/id_rsa.{{ sample_config_user }}.pub) }}"
        
    - name: correct sample-data users authorized_keys file acls
      file:
        path: "{{ sample_config_user_home }}/.ssh/authorized_keys"
        owner: "{{ sample_config_user }}"
        mode: "0600"

    - name: fetch sample-data user pub key
      fetch:
        src: "{{ sample_config_user_home }}/.ssh/id_rsa.{{ sample_config_user }}.pub"
        dest: "/tmp/"

    - name: fetch sample-data user priv key
      fetch:
        src: "{{ sample_config_user_home }}/.ssh/id_rsa.{{ sample_config_user }}"
        dest: "/tmp/"

    - name: copy sample configs
      copy:
        src: "sample-configs"
        dest: "{{ sample_config_user_home }}"
        owner: "{{ sample_config_user }}"
        group: "{{ fworch_user }}"

  become: yes
  