
- block:

    - name: install libs needed for pdf creator nuget packet HakanL/WkHtmlToPdf-DotNet
      package:
        name: "{{ item }}"
        state: present
      loop:
        - libjpeg62
        - libgdiplus

    - name: create ui dir
      file:
        dest: "{{ ui_dir }}"
        state: directory
        owner: "{{ fworch_user }}"
        group: "{{ fworch_group }}"

    - name: copy ui files to frontend target
      copy:
        src: "{{ item }}"
        dest: "{{ ui_dir }}"
        owner: "{{ fworch_user }}"
        group: "{{ fworch_group }}"
      loop:
        - FWO_UI

  become: yes

- include: ui_apache_install_and_setup.yml

- include: ui_install_dot_net.yml

