
- block:
    - name: Install webserver packages
      package: name={{ item }} state=present
      with_items:
        - "{{ webserver_package_name }}"
      environment: "{{ proxy_env }}"

    - name: enable apache modules proxy proxy_http ssl
      apache2_module: state=present name={{ item }}
      loop:
        - rewrite
        - proxy
        - proxy_http
        - ssl
        - proxy_wstunnel

    - name: copy ui httpd config file to ui target
      template:
        src: "httpd.conf"
        dest: "{{ http_conf_dir }}/{{ product_name }}-ui.conf"
        owner: root
        group: root
        
    - name: copy cert creation script to apache target and execute
      script: "apache_create_server_cert.sh" 

    - name: enable {{ product_name }} web site
      command: "a2ensite {{ product_name }}-ui"
      # todo: I received an error with the uncommented code below: module fworch does not exist
#      apache2_module:
#        state: present
#        name: "{{ product_name }}"
      register: testoutput

    - name: test
      debug:
        var: testoutput

    - name: increase apache timeout to 900 seconds
      lineinfile:
        path: /etc/apache2/apache2.conf
        line: "Timeout 900"

    - name: restart apache
      service:
       name: "{{ webserver_package_name }}"
       state: restarted     

  become: yes
  environment: "{{ proxy_env }}"
