- name: adding functions
  command: 'psql -d {{ fworch_db_name }} -c "\i {{ database_install_dir }}/sql/{{ item }}"'
  loop:
    - fworch-basic-procs.sql
    - fworch-import.sql
    - fworch-import-main.sql
    - fworch-obj-import.sql
    - fworch-obj-refs.sql
    - fworch-svc-import.sql
    - fworch-svc-refs.sql
    - fworch-usr-import.sql
    - fworch-usr-refs.sql
    - fworch-rule-import.sql
    - fworch-rule-refs.sql
    - fworch-zone-import.sql
    - fworch-report.sql
    - fworch-qa.sql
    - fworch-report-basics.sql
    - fworch-views.sql
    - fworch-grants.sql
  become: yes
  become_user: postgres
