- name: Check that docker bin is installed
  stat:
    path: /usr/bin/docker
  register: docker_is_installed

- block:
    - name: check if api container is running
      command: "docker ps -q --filter name={{ api_container_name }}"
      become: yes
      register: api_running

    - name: stop api container
      command: "docker stop {{ api_container_name }}"
      become: yes
      when: not api_running.stdout == ""

    - name: check if api container exists
      command: "docker ps --all -q --filter name={{ api_container_name }}"
      become: yes
      register: api_container_exists

    - name: remove api container
      command: "docker rm {{ api_container_name }}"
      become: yes
      when: not api_container_exists.stdout == ""
  when: docker_is_installed.stat.exists == True
