
- name: copy database test files to backend target
  copy: src="sql/test" dest="{{ database_install_dir }}/sql" owner="{{ fworch_user }}" group="{{ fworch_user }}"
  become: yes

- name: run db unit tests
  postgresql_query:
    db: "{{ fworch_db_name }}"
    path_to_script: "{{ database_install_dir }}/sql/test/{{ item }}"
  become: yes
  become_user: "postgres"
  register: testresults
  loop:
    - unit-tests.sql
    - import-test.sql
  tags:
    - unittest
    - test

- name: Print db test results
  debug: 
    msg: "test results: {{ testresults }}"

# - name: collect results of tests in list and check for "# Looks like you failed"
#   set_fact:
#     msg: "Key={{ item.0.key }} value={{ item.1 }}"
#   loop: "{{ testresults.results }}"    

# - name: Print db test status failure
#   fail: 
#     msg: "Some database unit tests failed: {{ testresults }}"
#   when: testresults.failed | bool

# - name: Print db test status success
#   debug: 
#     msg: "All database unit tests completed successfully"
#   when: not testresults.failed | bool

# - name: fail
#   fail:
#     msg: stopping after tests
