
- name: copy database test files to backend target
  copy: src="sql/test" dest="{{ database_install_dir }}/sql" owner="{{ fworch_user }}" group="{{ fworch_user }}"
  become: yes

- name: run db unit tests
  postgresql_query:
    db: "{{ fworch_db_name }}"
    path_to_script: "{{ database_install_dir }}/sql/test/{{ item }}"
  become: yes
  become_user: "postgres"
  register: testresults
  loop:
    - unit-tests.sql
    - unit-test-cleanup.sql
    - hasura-test.sql
  tags:
    - unittest
    - test

- name: Print db test results
  debug: 
    msg: "test results: {{ testresults | to_nice_json }}"
