- name: Check that docker bin is installed
  stat:
    path: /usr/bin/docker
  register: docker_is_installed

- name: stop api container
  docker_container:
    name: "{{ api_container_name }}"
    state: absent
  become: true
  when: docker_is_installed.stat.exists == True
