
- name: install upgrades normally
  postgresql_query:
    db: "{{ fworch_db_name }}"
    path_to_script: "{{ database_install_dir }}/upgrade/{{ item }}.sql"
  loop: "{{ upgrade_files | sort }}"
  ignore_errors: false
  become: true
  become_user: postgres
