---

tasks:
  - name: Check if ldap tree already exists
      shell: "ldapsearch ou=user -x | grep 'dn: ou=user,dc=fworch,dc=internal' | wc -l"
      register: is_ldap_present_flag

- block:
    - name: copy the ldif templates to system
      template:
        src: "{{ item }}"
        dest: /tmp/{{ item | basename | regex_replace('\.j2$', '') }}
      with_fileglob:
        # Frage: passt der file so?
        - ../templates/ldif_files/*.j2

    - name: Create organizational unit user
      command: "ldapmodify -H {{ auth_ldap_server_internal }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x -f /tmp/add_ou_user.ldif"

    - name: Create organizational unit user/systemuser
      command: "ldapmodify -H {{ auth_ldap_server_internal }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x -f /tmp/add_ou_systemuser.ldif"

    - name: Create organizational unit user/operator
      command: "ldapmodify -H {{ auth_ldap_server_internal }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x -f /tmp/add_ou_operator.ldif.j2"

    - name: Create common name user/systemuser/admin (GUI admin)
      command: "ldapmodify -H {{ auth_ldap_server_internal }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x -f /tmp/add_uid_admin.ldif"

    # todo: set password via ldappasswd to have a proper hash
  when: not is_ldap_present_flag

## Das ist nicht best practice, könnte andere ldif files treffen
#- name: delete all .ldif files in /tmp
#  file:
#    path: "{{ item }}"
#    state: absent
#  with_fileglob:
#    /tmp/*.ldif
