
- name: Check if ldap tree already exists
  shell: "ldapsearch -D uid=inspector,ou=systemuser,ou=user,dc=fworch,dc=internal -y /usr/local/fworch/etc/secrets/ldap_inspector_pw.txt ou=user -x | grep 'ou=user,{{ auth_ldap_path }}' | wc -l"
  register: is_ldap_present_flag

- block:
  - name: Decide on random {{ auth_ldap_internal_readonly_user }} password
    set_fact:
      ldap_inspector_pw: "{{ random_generated_pw }}"
      ldap_fgreporter_pwd: "{{ admin_pwd }}"

  - name: Write {{ auth_ldap_internal_readonly_user }} password to file
    copy:
      content: "{{ ldap_inspector_pw }}"
      dest: "{{ fworch_home }}/etc/secrets/ldap_inspector_pw.txt"
      mode: '0600'
      owner: "{{ fworch_user }}"
      group: "{{ fworch_user }}"

  - name: create ldif directory
    file:
      dest: "{{ auth_server_base_dir }}/ldif"
      state: directory
      owner: "{{ fworch_user }}"
      group: "{{ fworch_user }}"

  - name: copy the ldif templates to system
    template:
      src: "{{ item }}"
      dest: "{{ auth_server_base_dir }}/ldif/{{ item | basename | regex_replace('\\.j2$', '') }}"
    with_fileglob:
      - ../templates/ldif_files/*.j2

  - name: Create tree level 1 (ou user, role)
    command: "ldapmodify -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x -f {{ auth_server_base_dir }}/ldif/add_tree_level_1.ldif"

  - name: Create tree level 2 (ou systemuser, operator)
    command: "ldapmodify -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x -f {{ auth_server_base_dir }}/ldif/add_tree_level_2.ldif"

  - name: Create tree level 3 with parent systemuser (cn admin, {{ auth_ldap_internal_readonly_user }}, fgreporter)
    command: "ldapmodify -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x -f {{ auth_server_base_dir }}/ldif/add_tree_level_3_with_parent_systemuser.ldif"

  - name: Create tree level 3 with parent operator (ou tenant0, tenant1, tenant2)
    command: "ldapmodify -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x -f {{ auth_server_base_dir }}/ldif/add_tree_level_3_with_parent_operator.ldif"

  - name: set admin password in ldap
    command: "ldappasswd -s {{ admin_pwd }} -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x 'uid=admin,ou=systemuser,ou=user,{{ auth_ldap_path }}'"

  - name: set fgreporter password in ldap
    command: "ldappasswd -s {{ ldap_fgreporter_pwd }} -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x 'uid=fgreporter,ou=systemuser,ou=user,{{ auth_ldap_path }}'"

  - name: set {{ auth_ldap_internal_readonly_user }} password in ldap
    command: "ldappasswd -s {{ ldap_inspector_pw }} -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x 'uid={{ auth_ldap_internal_readonly_user }},ou=systemuser,ou=user,{{ auth_ldap_path }}'"

  - name: Create tree level 4 with parent tenantx (cn admin)
    command: "ldapmodify -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x -f {{ auth_server_base_dir }}/ldif/add_tree_level_4.ldif"

  - name: set admin password in ldap
    command: "ldappasswd -s {{ admin_pwd }} -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x 'uid=admin,ou=tenant0,ou=operator,ou=user,{{ auth_ldap_path }}'"

  - name: delete ldif files
    file:
      path: "{{ auth_server_base_dir }}/ldif"
      state: absent
  when: is_ldap_present_flag.stdout == "0"
  become: yes
