- block:  
   - name: make sure secrets dir exists
     file:
        path: "{{ fworch_home }}/etc/secrets"
        state: directory
        mode: "0700"
        owner: "{{ fworch_user }}"
        group: "{{ fworch_user }}"

   - set_fact: api_home="{{ fworch_home }}/api"

   - name: generate jwt secret
     shell: "< /dev/urandom tr -dc a-f0-9 | head -c${1:-512}"
     register: jwt_secret

   - set_fact: api_hasura_jwt_secret="{{ jwt_secret.stdout }}"

   - name: write api_hasura_jwt_secret into file for reference
     lineinfile:
        path: "{{ fworch_home }}/etc/secrets/jwt_private.key"
        line: "{{ jwt_secret.stdout }}"
        regexp: ".*"    # match every line and replace it (only one line expected)
        create: yes
        mode: "0600"
        owner: "{{ fworch_user }}"
        group: "{{ fworch_user }}"
        backup: yes

  become: yes
