- block:  
    - name: make sure secrets dir exists
      file:
        path: "{{ fworch_home }}/etc/secrets"
        state: directory
        mode: "0700"
        owner: "{{ fworch_user }}"
        group: "{{ fworch_user }}"

    - name: set auth fact ldif changetype
      set_fact:
        change_local_ldap: yes

    - name: check if there already is an ldap connection in DB
      command: psql -qtAX -d {{ fworch_db_name | quote }} -c "SELECT COUNT(*) FROM ldap_connection"
      become: yes
      become_user: postgres
      register: ldap_conn_present

    # - debug:
    #     var: ldap_conn_present
    #     # msg: "ldap conn check result: {{ ldap_conn_present.stdout }}"

    - name: change value for ldif_changetype to modify if ldap conn alread exists
      set_fact:
        change_local_ldap: no
      when: ldap_conn_present.stdout == "1"

    - name: read ldap manager pwd from file
      slurp:
        src: "{{ fworch_home }}/etc/secrets/ldap_manager_pw.txt"
      register: ldap_manager_secret_dict
      become: yes

    - name: decode ldap manager pwd
      set_fact:
        ldap_manager_pwd_decoded: "{{ ldap_manager_secret_dict['content'] | b64decode }}"

    - name: remove unwanted and unexplainable suffix backslash+n plus curly closing bracket from key
      set_fact:
        ldap_manager_pwd: "{{ ldap_manager_pwd_decoded.split('\n')[0] }}"

    - name: generate jwt secret
      shell: "< /dev/urandom tr -dc a-f0-9 | head -c${1:-512}"
      register: secret512

    - set_fact: api_hasura_jwt_secret="{{ secret512.stdout }}"

    - name: write api_hasura_jwt_secret into file for reference
      lineinfile:
        path: "{{ fworch_home }}/etc/secrets/jwt_private.key"
        line: "{{ api_hasura_jwt_secret }}"
        regexp: ".*"    # match every line and replace it (only one line expected)
        create: yes
        mode: "0600"
        owner: "{{ fworch_user }}"
        group: "{{ fworch_user }}"
        backup: yes

    - name: generate ldap local readonly secret
      shell: "< /dev/urandom tr -dc a-f0-9 | head -c${1:-32}"
      register: secret32

    - set_fact: api_ldap_inspector_pw="{{ secret32.stdout }}"

  become: yes
