# source: https://github.com/michelp/pgjwt

- name: include pgjwt
  include auth_pgjwt

- name: add standard roles
  include auth_standard_roles

- name: add auth test data
  include auth_test_data

- name: create auth directory
  file:
    dest: "{{ iso_home }}/auth"
    state: directory
    owner: "{{ iso_user }}"
    group: "{{ iso_user }}"
  become: yes

- name: copy authentication sql file
  copy:
    src: pre_auth_functions.sql
    dest: "{{ iso_home }}/auth/"
    owner: "{{ iso_user }}"
    group: "{{ iso_user }}"
  become: yes

- name: create funtions needed during authentication
  shell: 'psql -d {{ iso_db_name }} -c "\i {{ iso_home }}/auth/pre_auth_functions.sql"'
  become: yes
  become_user: postgres
