
- name: create auth directory
  file:
    dest: "{{ auth_server_base_dir }}"
    state: directory
    owner: "{{ fworch_user }}"
    group: "{{ fworch_user }}"
  become: yes

- name: set default value for ldif_changetype
  set_fact:
    ldif_changetype: add

- name: check if there already is an ldap connection in DB
  shell: psql -d {{ fworch_db_name | quote }} -c "DO \$do\$ BEGIN IF NOT EXISTS (SELECT * FROM ldap_connection) THEN RAISE DEBUG 'LDAP Connection already present'; END IF; END \$do\$"
  become: yes
  become_user: postgres
  register: ldap_conn_present

- name: change value for ldif_changetype to modify if ldap conn alread exists
  set_fact:
    ldif_changetype: modify
  when: ldap_conn_present.stdout == 'LDAP Connection already present'

- name: Set new random {{ auth_ldap_internal_readonly_user }} password every time
  set_fact:
    ldap_inspector_pw: "{{ random_generated_pw }}"

# - name: add standard roles with ansible 2.8 and above
#   include_tasks: auth_standard_roles_with_postgresql_query.yml
#   when: ansible_version.full >= "2.8"

# # todo: remove, when ansible 2.8 is available for all supported platforms and use above module
# - name: add standard roles with command
#   include_tasks: auth_standard_roles_with_command.yml
#   when: ansible_version.full < "2.8"

- name: copy authentication sql file
  copy:
    src: pre_auth_functions.sql
    dest: "{{ fworch_home }}/auth/"
    owner: "{{ fworch_user }}"
    group: "{{ fworch_user }}"
  become: yes

- name: create functions needed during authentication
  command: 'psql -d {{ fworch_db_name }} -c "\i {{ fworch_home }}/auth/pre_auth_functions.sql"'
  become: yes
  become_user: postgres

- name: copy auth module files to authserver
  copy:
    src: "{{ auth_path_rel }}"
    dest: "{{ auth_server_base_dir }}"
    owner: "{{ fworch_user }}"
    group: "{{ fworch_user }}"
  become: yes

- name: create jwt key
  include_tasks: create_jwt_key.yml

- name: install dot net
  import_tasks: auth_install_dot_net.yml

- name: build ldap tree
  import_tasks: create_ldap_tree.yml

- name: add local ldap connection
  shell: psql -d {{ fworch_db_name | quote }} -c "DO \$do\$ BEGIN IF NOT EXISTS (SELECT * FROM ldap_connection) THEN INSERT INTO ldap_connection (ldap_server, ldap_port, ldap_searchpath_for_users, ldap_tenant_level, ldap_search_user, ldap_search_user_pwd) VALUES ('{{ auth_ldap_server_internal | quote }}', 636, '{{ auth_ldap_std_user_path | quote }}', 1, '{{ auth_ldap_internal_readonly_user | quote }}', '{{ ldap_inspector_pw }}'); END IF; END \$do\$"
  become: yes
  become_user: postgres
