
- name: create auth directory
  file:
    dest: "{{ auth_server_base_dir }}"
    state: directory
    owner: "{{ fworch_user }}"
    group: "{{ fworch_user }}"
  become: yes

- name: add standard roles with ansible 2.8 and above
  import_tasks: auth_standard_roles_with_postgresql_query.yml
  when: ansible_version.full >= "2.8"

# todo: remove, when ansible 2.8 is available for all supported platforms and use above module
- name: add standard roles with command
  import_tasks: auth_standard_roles_with_command.yml
  when: ansible_version.full < "2.8"

- name: copy authentication sql file
  copy:
    src: pre_auth_functions.sql
    dest: "{{ fworch_home }}/auth/"
    owner: "{{ fworch_user }}"
    group: "{{ fworch_user }}"
  become: yes

- name: create funtions needed during authentication
  command: 'psql -d {{ fworch_db_name }} -c "\i {{ fworch_home }}/auth/pre_auth_functions.sql"'
  become: yes
  become_user: postgres

- name: copy auth module files to authserver
  copy:
    src: "{{ auth_path_rel }}"
    dest: "{{ auth_server_base_dir }}"
    owner: "{{ fworch_user }}"
    group: "{{ fworch_user }}"
  become: yes

- name: install dot net
  import_tasks: auth_install_dot_net.yml

- name: build ldap tree
  import_tasks: create_ldap_tree.yml
