
- name: add external ldap test connection
  postgresql_query:
    db: "{{ fworch_db_name }}"
    query: >
      DO $do$ BEGIN IF NOT EXISTS
      (SELECT * FROM ldap_connection WHERE ldap_server='{{ test_ldap_external_ad_server }}')
      THEN INSERT INTO ldap_connection
      (ldap_server, ldap_port, ldap_searchpath_for_users, ldap_tenant_level,
      ldap_search_user, ldap_search_user_pwd, ldap_tls)
      VALUES
      ('{{ test_ldap_external_ad_server }}', {{ test_ldap_external_ad_port }},
      '{{ test_ldap_external_ad_user_search_path }}', 1,
      '{{ test_ldap_external_ad_user_fq_name }}', '{{ test_ldap_external_ad_user_pwd }}',
      {{ test_ldap_external_ad_tls }});
      END IF; END $do$
  become: yes
  become_user: postgres
  when: test_ldap_external_ad_add_connection == "yes"
  