
- name: add external ldap test connection
  shell: psql -d {{ fworch_db_name | quote }} -c "DO \$do\$ BEGIN IF NOT EXISTS (SELECT * FROM ldap_connection WHERE ldap_server='{{ test_ldap_external_server | quote }}') THEN INSERT INTO ldap_connection (ldap_server, ldap_port, ldap_searchpath_for_users, ldap_tenant_level, ldap_search_user, ldap_search_user_pwd, ldap_tls) VALUES ('{{ test_ldap_external_server | quote }}', {{ test_ldap_external_port | quote }}, '{{ test_ldap_external_user_search_path | quote }}', 1, '{{ test_ldap_external_user_fq_name | quote }}', '{{ test_ldap_external_user_pwd }}', {{ test_ldap_external_tls }}); END IF; END \$do\$"
  become: yes
  become_user: postgres
  when: auth_change_local_ldap == "yes"
  