- block:

  - name: insert tenant tenant1_{{ sample_postfix }}
    postgresql_query:
      db: "{{ fworch_db_name }}"
      query: >
        DO $do$ BEGIN
          IF NOT EXISTS (SELECT tenant_id FROM tenant WHERE tenant_name='tenant1_{{ sample_postfix }}') THEN
            insert into tenant (tenant_name, tenant_can_view_all_devices, tenant_is_superadmin) 
              values ('tenant1_{{ sample_postfix }}', false, false); 
          END IF; 
        END $do$

  - name: add devices for tenant tenant1_{{ sample_postfix }}
    postgresql_query:
      db: "{{ fworch_db_name }}"
      query: >
        DO $do$ BEGIN 
          IF NOT EXISTS (SELECT * FROM tenant_to_device LEFT JOIN tenant USING (tenant_id) WHERE tenant_name='tenant1_{{ sample_postfix }}') THEN 
            INSERT INTO tenant_to_device (tenant_id, device_id)
            SELECT tenant_id, (select dev_id FROM device where device.dev_name='fortigate_{{ sample_postfix }}') from tenant WHERE tenant.tenant_name='tenant1_{{ sample_postfix }}'; 
          END IF; 
        END $do$

  - name: insert tenant tenant2_{{ sample_postfix }}
    postgresql_query:
      db: "{{ fworch_db_name }}"
      query: >
        DO $do$ BEGIN
          IF NOT EXISTS (SELECT tenant_id FROM tenant WHERE tenant_name='tenant2_{{ sample_postfix }}') THEN
            insert into tenant (tenant_name, tenant_can_view_all_devices, tenant_is_superadmin) 
              values ('tenant2_{{ sample_postfix }}', false, false); 
          END IF; 
        END $do$

  - name: add devices for tenant tenant2_{{ sample_postfix }}
    postgresql_query:
      db: "{{ fworch_db_name }}"
      query: >
        DO $do$ BEGIN 
          IF NOT EXISTS 
            (SELECT * FROM tenant_to_device LEFT JOIN tenant USING (tenant_id) WHERE tenant_name='tenant2_{{ sample_postfix }}') THEN 
            INSERT INTO tenant_to_device (tenant_id, device_id) 
          SELECT tenant_id, (select dev_id FROM device where device.dev_name='checkpoint_{{ sample_postfix }}') from tenant WHERE tenant.tenant_name='tenant2_{{ sample_postfix }}'; 
          END IF; 
        END $do$
    when: sample_role_purpose is not match('test')

  become: yes
  become_user: postgres
