# this playbook sets up some sample auth data (roles, users)

- name: add auth test data to database
  include_tasks: auth_test_data.yml

- name: Check if ldap sample-auth-data already exists
  shell: "ldapsearch ou=forti -x | grep 'ou=forti,{{ auth_ldap_std_user_path }}' | wc -l"
  register: is_sample_auth_present_flag

- block:
  - name: copy ldif template for roles
    template:
      src: add_ou_test_roles.ldif.j2
      dest: "{{ fworch_home }}/auth/add_ou_test_roles.ldif"
    become: yes

  - name: Create test roles in ldap
    command: "ldapmodify -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x -f {{ fworch_home }}/auth/add_ou_test_roles.ldif"

  - name: copy ldif template for users
    template: src=add_uid_test_users.ldif.j2 dest={{ fworch_home }}/auth/add_uid_test_users.ldif
    become: yes

  - name: Create test users in ldap
    command: "ldapmodify -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x -f {{ fworch_home }}/auth/add_uid_test_users.ldif"

  - name: set user fgreporter password in ldap
    command: "ldappasswd -s {{ auth_ldap_user_inital_pwd }} -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x 'uid=fgreporter,ou=forti,{{ auth_ldap_std_user_path }}'"

  - name: set user checkreporter password in ldap
    command: "ldappasswd -s {{ auth_ldap_user_inital_pwd }} -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x 'uid=checkreporter,ou=check,{{ auth_ldap_std_user_path }}'"

  - name: set user viewallreporter password in ldap
    command: "ldappasswd -s {{ auth_ldap_user_inital_pwd }} -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x 'uid=viewallreporter,ou=viewall,{{ auth_ldap_std_user_path }}'"
  when: is_sample_auth_present_flag.stdout == "0"

  # todo: remove ldif files