# this playbook sets up some sample auth data (roles, users)

- name: add auth test data to database
  include_tasks: auth_test_data.yml

- block:
  - name: copy ldif template for roles
    template:
      src: add_ou_test_roles.ldif.j2
      dest: "{{ fworch_home }}/auth/add_ou_test_roles.ldif"
    become: yes

  - name: Create test roles in ldap
    command: "ldapmodify -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x -f {{ fworch_home }}/auth/add_ou_test_roles.ldif"

  - name: copy ldif template for users
    template: src=add_uid_test_users.ldif.j2 dest={{ fworch_home }}/auth/add_uid_test_users.ldif
    become: yes

  - name: Create test users in ldap
    command: "ldapmodify -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x -f {{ fworch_home }}/auth/add_uid_test_users.ldif"

  - name: set user viewallreporter password in ldap
    command: "ldappasswd -s {{ auth_ldap_user_inital_pwd }} -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x 'uid=viewallreporter,ou=viewall,{{ auth_ldap_std_user_path }}'"
  when: auth_change_local_ldap == 'yes'

  # todo: remove ldif files