# this playbook sets up some sample auth data (roles, users)

- name: add auth test data to database
  include_tasks: auth_sample_data.yml

- name: add auth test ext. ldap to database
  include_tasks: auth_sample_ext_ldap.yml

# - name: delete complete ldap tree
#   command: "ldapdelete -r -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ ldap_manager_pwd }} -x '{{ auth_ldap_path }}'"
#   ignore_errors: yes

- name: include ldif driven changes
  import_tasks: modify_ldap_tree.yml

- block:

  # - name: copy ldif template for roles
  #   template:
  #     src: add_ou_test_roles.ldif.j2
  #     dest: "{{ fworch_home }}/auth/add_ou_test_roles.ldif"
  #   become: yes

  # - name: Create test roles in ldap
  #   command: "ldapmodify -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x -f {{ fworch_home }}/auth/add_ou_test_roles.ldif"

  # - name: copy ldif template for users
  #   template: src=add_uid_test_users.ldif.j2 dest={{ fworch_home }}/auth/add_uid_test_users.ldif
  #   become: yes

  # - name: Create test users in ldap
  #   command: "ldapmodify -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x -f {{ fworch_home }}/auth/add_uid_test_users.ldif"

  # - name: set user viewallreporter password in ldap
  #   command: "ldappasswd -s {{ auth_ldap_user_inital_pwd }} -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x 'uid=viewallreporter,ou=viewall,{{ auth_ldap_std_user_path }}'"

  - name: copy ldif template for example roles
    template:
      src: modify_example_roles.ldif.j2
      dest: "{{ fworch_home }}/auth/modify_example_roles.ldif"
    become: yes

  - name: Pass example roles
    command: "ldapmodify -H {{ auth_ldap_internal_url }} -D {{ auth_ldap_superuser_name }} -w {{ openldap_server_random_rootpw }} -x -f {{ fworch_home }}/auth/modify_example_roles.ldif"

  when: auth_change_local_ldap == 'yes'

- name: restart auth server in case any changes to ldap_connections were made
  command: "systemctl restart {{ auth_service_name }}"
  become: yes

  # todo: remove ldif files
