- name: copy the ldif templates to system once more (this time for adding entries)
  template:
    src: "{{ item }}"
    dest: "{{ middleware_ldif_dir }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
    force: yes
  with_fileglob:
    - ../templates/tree_*.j2
  become: yes

- name: add tree
  command: "ldapmodify -H {{ openldap_url }} -D {{ openldap_superuser_dn }} -y {{ fworch_secrets_dir }}/ldap_manager_pw.txt -x -f {{ middleware_ldif_dir }}/tree_{{ item }}.ldif"
  loop:
    - sample_tenants
    - sample_operators
    - sample_groups
    - roles_for_sample_operators
    - groups_for_sample_operators
  when: "not installation_mode == 'upgrade'"
  become: yes
