---
- name: recover backup
  synchronize:
    src: "{{ fworch_home }}/backup_api/api"
    dest: "{{ fworch_home }}"
  delegate_to: "{{ inventory_hostname }}"
  listen: "api handler"
  when: api_handler_guard == "start"
  become: yes

- name: delete backup
  file:
    state: absent
    path: "{{ fworch_home }}/backup_api"
  listen: "api handler"
  become: yes
