- name: copy associated ldif files to system
  template:
    src: 5.4.1.ldif.j2
    dest: "{{ ldif_dir }}/5.4.1.ldif"

- name: upgrade olcAccess policy
  command: "ldapmodify -H {{ openldap_url }} -D cn=config -w {{ ldap_manager_pwd }} -x -f {{ ldif_dir }}/5.4.1.ldif"
