- name: rename ldap manager pwd file 
  copy:
    src: "{{ fworch_secrets_dir }}/ldap_manager_pw.txt"
    dest: "{{ ldap_manager_pwd_file }}"
    force: yes
    remote_src: yes
  become: yes
  ignore_errors: true
