---
- block:
  - name: Add the OS specific varibles
    include_vars: "{{ ansible_os_family }}.yml"

  # - name: Install the openldap and required Packages for RedHat
  #   yum: name={{ item }} state=present
  #   with_items: openldap_server_pkgs
  #   when: ansible_os_family == 'RedHat'

  - name: Install the openldap and required Packages for Ubuntu
    package: 
      name: "{{ item }}"
      state: present 
    loop: "{{ openldap_server_pkgs }}"
    # environment: env
    # when: ansible_os_family == 'Debian'

  - name: Delete the configuration directory
    file: 
      path: "{{ openldap_server_app_path }}/slapd.d"
      state: absent

  - name: Check if manager password exist
    stat:
      path: "{{ fworch_home }}/etc/secrets/ldap_manager_pw.txt"
    register: is_manger_pw_present_flag

  - name: Decide on random manager password
    set_fact:
      openldap_server_random_rootpw: "{{ random_generated_pw }}"
    when: is_manger_pw_present_flag is defined

  - name: Write random manager password to file
    copy:
      content: "{{ openldap_server_random_rootpw }}"
      dest: "{{ fworch_home }}/etc/secrets/ldap_manager_pw.txt"
      mode: '0600'
      owner: "{{ fworch_user }}"
      group: "{{ fworch_user }}"
    when: is_manger_pw_present_flag is defined

  - name: Generate the root password for ldap
    shell: "slappasswd -s {{ openldap_server_random_rootpw }} "
    register: root_password

  # - name: Copy the slapd.conf configuration file for Redhat
  #   template:
  #     src: slapd.conf.j2
  #     dest: "{{ openldap_server_app_path }}/slapd.conf"
  #   when: ansible_os_family == "RedHat"
  #   notify: 
  #   - restart slapd

  - name: Copy the slapd.conf configuration file
    template: src=slapd.conf_ubuntu.j2 dest={{ openldap_server_app_path }}/slapd.conf
#    when: ansible_os_family == "Debian"
    notify: 
    - restart slapd
  
  - name: Copy the ldap.conf configuration file
    template: src=ldap.conf.j2 dest={{ openldap_server_app_path }}/ldap.conf

  become: yes
