---
- block:
  - name: Add the OS specific varibles
    include_vars: "{{ ansible_os_family }}.yml"

  # - name: Install the openldap and required Packages for RedHat
  #   yum: name={{ item }} state=present
  #   with_items: openldap_server_pkgs
  #   when: ansible_os_family == 'RedHat'

  - name: Install the openldap and required Packages for Ubuntu
    package: 
      name: "{{ item }}"
      state: present 
    loop: "{{ openldap_server_pkgs }}"
    # environment: env
    # when: ansible_os_family == 'Debian'

    #todo: delete
  - name: Pause for 5 minutes to test
    pause:
      minutes: 5

  - name: Delete the configuration directory
    file:
      path: "{{ openldap_server_app_path }}/slapd.d"
      state: absent
    when: openldap_first_install == 'yes'

  - name: Create the configuration directory
    file:
      path: "{{ openldap_server_app_path }}/slapd.d"
      state: directory

#  - name: Copy slap initial file to system if not present
#    copy:
#      src: config.ldif
#      dest: "{{ openldap_server_app_path }}/slapd.d/"
#      force: no

  - name: Initialize ldap config
    command: slapadd -F /etc/ldap/slapd.d -n 0 -l config.ldif
    when: openldap_first_install == 'yes'
    register: ldap_initialization

  - name: Debug ldap initialization
    debug:
      var: ldap_initialization.stdout_lines

  - name: Check if manager password exist
    stat:
      path: "{{ openldap_secrets_path }}/ldap_manager_pw.txt"
    register: is_manger_pw_present_flag

  - name: Decide on random manager password
    set_fact:
      openldap_server_random_rootpw: "{{ random_generated_pw }}"
    when: not is_manger_pw_present_flag.stat.exists

  - name: Write random manager password to file
    copy:
      content: "{{ openldap_server_random_rootpw }}"
      dest: "{{ openldap_secrets_path }}/ldap_manager_pw.txt"
      mode: '0600'
      owner: "{{ fworch_user }}"
      group: "{{ fworch_user }}"
    when: not is_manger_pw_present_flag.stat.exists

  - name: Generate the root password hash for the config
    shell: "slappasswd -T {{ openldap_secrets_path }}/ldap_manager_pw.txt"
    register: root_password

  # - name: Copy the slapd.conf configuration file for Redhat
  #   template:
  #     src: slapd.conf.j2
  #     dest: "{{ openldap_server_app_path }}/slapd.conf"
  #   when: ansible_os_family == "RedHat"
  #   notify: 
  #   - restart slapd

#  - name: Copy the slapd.conf configuration file
#    template:
#      src: slapd.conf_{{ openldap_current_role }}.j2
#      dest: "{{ openldap_server_instance_path }}/slapd.conf"
##    when: ansible_os_family == "Debian"
#    notify:
#    - restart slapd
  
  - name: Copy the ldap.conf configuration file
    template:
      src: ldap.conf.j2
      dest: "{{ openldap_server_instance_path }}/ldap.conf"

  become: yes
