---
- name: install pip3
  package:
    name: python3-pip
    state: present
  become: yes

- name: install python3-virtualenv
  package:
    name: python3-virtualenv
    state: present
  become: yes

- name: pip install all packages for docker in user context
  pip:
     name: docker
     virtualenv: "{{ api_venv_dir }}"
  environment:
    HTTP_PROXY: "http_proxy"
    HTTPS_PROXY: "https_proxy"
  become: yes
  become_user: "{{ iso_user }}"

- name: Append the group 'docker' for ansible_user to enable him/her to run docker
  user:
     name: "{{ iso_user }}"
     groups: docker
     append: yes
  become: yes

- name: create local user docker config dir .docker
  file:
    dest: "{{ iso_home }}/.docker"
    state: directory
    mode: 0775
  become: yes
  become_user: "{{ iso_user }}"

#- name: create local user docker config file .docker/config.json
#  template:
#    src: docker_config.j2
#    dest: "{{ iso_home }}/.docker/config.json"
#    mode: 0644
#  become: yes
#  become_user: "{{ iso_user }}"
