---

- name: Network Getting Started First Playbook
  connection: network_cli
  gather_facts: false
  hosts: all
  become: yes
  tasks:

########## general packages ##################

    - name: find out installed postgres version
      script: "get_pg_version.sh"
      register: pg_version_result
      changed_when: false

    - name: set fact pg_version
      set_fact:
         pg_version: "{{ pg_version_result.stdout }}"      

    - name: install general packages
      package:
         name: "{{ item }}"
      loop:
        - rsyslog
        - "{{ web_server_name }}"
        - gnupg2
        - apt-transport-https
        - ca-certificates 
        - curl 
        - software-properties-common
        - npm
        - python3-pip
        - python3-virtualenv
        - python3-psycopg2
        - libpq-dev
        - "{{ postgresql_package }}"
        - libpq-dev
        - postgresql-client

########## ldap ##################

    - name: Install the openldap and required Packages
      package: 
        name: "{{ item }}"
        state: present 
      loop: "{{ openldap_server_pkgs }}"

########## docker for api ##################

    - name: add apt signing key for docker
      shell: "wget -qO - -e use_proxy=yes -e https_proxy={{ https_proxy }} https://download.docker.com/linux/ubuntu/gpg | apt-key add -"
      when: https_proxy is defined

    - name: add docker repo
      lineinfile:
        path: "/etc/apt/sources.list.d/docker.list"
        create: yes
        line: "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"

    - name: apt update
      apt: update_cache=true
      environment: "{{ proxy_env }}"

    - name: install docker specific packages from specific repo
      package:
         name: "{{ item }}"
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

########## dotnet ##################

    - set_fact: distribution_version="{{ ansible_facts['distribution_version'] }}"
      when: ansible_facts['distribution']|lower == 'ubuntu'

    - set_fact: distribution_version="{{ ansible_facts['distribution_version'] | regex_replace('\.\d$','') }}"
      when: ansible_facts['distribution']|lower == 'debian'

    - name: get package list from ms {{ dotnet_deb_name }}
      get_url:
        url: "https://packages.microsoft.com/config/{{ ansible_facts['distribution']|lower }}/{{ distribution_version }}/{{ dotnet_deb_name }}"
        dest: "{{ ui_dir }}/{{ dotnet_deb_name }}"
        mode: "0644"

    - name: install ms package list
      command: "dpkg -i {{ ui_dir }}/{{ dotnet_deb_name }}"

    - name: remove package list file
      file:
        dest: "{{ ui_dir }}/{{ dotnet_deb_name }}"
        state: absent

    - name: apt update
      apt: update_cache=true

    - name: Install dotnet-sdk-{{ dotnet_version }}
      package: "name=dotnet-sdk-{{ dotnet_version }} state=present"
     
     
########## importer ##################

    - name: install importer packages
      package:
         name: "{{ item }}"
      loop:
        - libdbi-perl 
        - libdbd-pg-perl 
        - libdate-calc-perl 
        - psmisc 
        - libnet-cidr-perl 
        - libsys-syslog-perl 
        - libexpect-perl
        - libcgi-pm-perl

########## postgres dev/test ##################

    - set_fact:
        postgresql_dev_package: "{{ postgresql_dev_package_prefix }}-{{ pg_version }}"

    - name: install pg_dev packages
      package:
         name: "{{ item }}"
      loop:
        - make
        - "{{ postgresql_dev_package }}"
        - "{{ postgresql_test_package }}"
        
########## old php ui ##################
        
    - name: install php packages
      package:
         name: "{{ item }}"
      loop:
        - apache2
        - php
        - libapache2-mod-php
        - php-pgsql
        - php-pear
