- block: 

  - name: create symlink /usr/local/fworch/etc to /etc/fworch
    file:
      src: "{{ fworch_home }}/etc"
      dest: "/etc/{{ prod_name }}"
      state: link

  # - name: create temp symlink necessary for rel path to conf file in csharp debugging
  #   file:
  #     src: "{{ fworch_home }}/etc"
  #     dest: "/usr/etc"
  #     state: link

      # settings used within c# source code only
  - name: edit central conf file
    blockinfile:
      path: "{{ fworch_conf_file }}"
      create: yes
      block: |
        # general settings
        fworch_home: "{{ fworch_home }}"
        dotnet_mode: "{{ dotnet_mode }}"
        
        # api
        api_uri: "https://{{ api_ip_address }}:{{ api_web_port }}/api/v1/graphql"
        api_hasura_jwt_alg: "{{ api_hasura_jwt_alg }}"
        
        # auth
        auth_JWT_key_file: "{{ jwt_private_key_file }}"
        auth_hostname: "{{ auth_hostname }}"
        auth_server_port: "{{ auth_web_listener_port }}"

  become: yes
