- block: 

  - name: fetch remote config file
    fetch:
      src: "{{ fworch_conf_file }}"
      dest: "temp_remote_config_file.yml"
      flat: yes
    when: already_installed and installation_mode == "upgrade"

  - name: read config file of currently installed product
    include_vars: 
      file: "temp_remote_config_file.yml"
      name: config
    when: already_installed and installation_mode == "upgrade"

  - name: remove local copy of remote config file
    file:
      state: absent
      name: "temp_remote_config_file.yml"

  - name: create symlink /usr/local/fworch/etc to /etc/fworch
    file:
      src: "{{ fworch_home }}/etc"
      dest: "/etc/{{ product_name }}"
      state: link

  - name: get version of currently installed product
    set_fact: 
      old_version: "{{ config.product_version }}"
    when: already_installed and installation_mode == "upgrade"

  - name: write new version of product to config file
    lineinfile:
      path: "{{ fworch_conf_file }}"
      regexp: "^product_version:"
      line: "product_version: {{ product_version }}"
      backup: yes
    when: installation_mode == "upgrade"

  - name: edit central conf file
    blockinfile:
      path: "{{ fworch_conf_file }}"
      create: yes
      block: |
        # general settings
        fworch_home: "{{ fworch_home }}"
        dotnet_mode: "{{ dotnet_mode }}"
        product_version: "{{ product_version }}"
        
        # api
        api_uri: "https://{{ api_ip_address }}:{{ api_web_port }}/api/v1/graphql"
        api_hasura_jwt_alg: "{{ api_hasura_jwt_alg }}"
        
        # middleware
        middleware_uri: "http://{{ middleware_hostname }}:{{ middleware_web_listener_port }}/"
        # should be middleware_uri: "https://{{ middleware_hostname }}:{{ middleware_web_listener_port }}/"
    when: installation_mode != "upgrade"
    # keep old version number in config file until end of upgrade

  become: yes
