- block: 

  # settings used within c# source code only
  - name: edit central conf file
    blockinfile:
      path: "{{ fworch_conf_file }}"
      create: yes
      block: |
        # general settings
        fworch_home: "{{ fworch_home }}"
        dotnet_mode: "{{ dotnet_mode }}"
        
        # api
        api_uri: "https://{{ api_hostname }}:{{ api_web_port }}/api/v1/graphql"
        api_hasura_jwt_alg: "{{ api_hasura_jwt_alg }}"
        
        # auth
        auth_JWT_key_file: "{{ auth_JWT_key_file }}"
        auth_hostname: "{{ auth_hostname }}"
        auth_server_port: "{{ auth_web_listener_port }}"

  become: yes
