
- name: install package rsyslog
  package:
    name: "rsyslog"
    state: present
  become: yes

- name: create log dir for {{ product_name }} on ubuntu - owner syslog
  file:
    path: "/var/log/{{ product_name }}/"
    state: directory
    owner: syslog
    group: syslog
    mode: "0775"
  become: yes
  when: ansible_facts['distribution'] == "Ubuntu"
    
- name: create log dir for {{ product_name }} on debian - owner root
  file:
    path: "/var/log/{{ product_name }}/"
    state: directory
    owner: root
    group: root
    mode: "0775"
  become: yes
  when: ansible_facts['distribution'] == "Debian"

- name: change rsyslog config to receive logs
  blockinfile:
    path: /etc/rsyslog.conf
    block: |
      module(load="im{{ syslog_proto }}")
      input(type="im{{ syslog_proto }}" port="{{ syslog_port }}")
  become: yes

- name: create log dir for {{ product_name }} on redhat - owner root
  file:
    path: "/var/log/{{ product_name }}/"
    state: directory
    owner: root
    group: root
    mode: "0775"
  when: ansible_facts['distribution'] == "RedHat"
  become: yes

- name: create db log file for {{ product_name }} - owner postgres
  file:
    path: "/var/log/{{ product_name }}/database.log"
    state: touch
    owner: postgres
    group: adm
    mode: "0640"
  become: yes

- name: edit rsyslog to include fworch file logging
  blockinfile:
    path: "/etc/rsyslog.d/30-{{ product_name }}.conf"
    create: yes
    block: |
      # syslog for {{ product_name }}; Log {{ product_name }} log messages to file

      # change date format to ISO and contain timezone and remove process id
      template(name="fworch" type="list") {
        property(name="timereported" dateFormat="rfc3339")
        constant(value=" ") property(name="hostname")
        constant(value=" ") property(name="programname")
        constant(value=": ")
        property(name="msg" spifno1stsp="on")
        property(name="msg" droplastlf="on")
        constant(value="\n")
      }

      if $programname == '{{ product_name }}-database' then action(type="omfile" file="/var/log/{{ product_name }}/database.log" template="fworch")
      if $programname == '{{ middleware_server_syslog_id }}' then action(type="omfile" file="/var/log/{{ product_name }}/middleware.log" template="fworch")
      if $programname == '{{ ui_syslog_id }}' then action(type="omfile" file="/var/log/{{ product_name }}/ui.log" template="fworch")
      if $programname == '{{ ldap_syslog_id }}' then action(type="omfile" file="/var/log/{{ product_name }}/ldap.log" template="fworch")
      if $programname == '{{ product_name }}-api' then action(type="omfile" file="/var/log/{{ product_name }}/api.log" template="fworch")
      if $programname startswith '{{ product_name }}-importer-legacy' then action(type="omfile" file="/var/log/{{ product_name }}/importer-legacy.log" template="fworch")
      if $programname startswith '{{ product_name }}-importer-api' then action(type="omfile" file="/var/log/{{ product_name }}/importer-api.log" template="fworch")
      if $programname startswith '{{ product_name }}' and $msg contains "Audit" then action(type="omfile" file="/var/log/{{ product_name }}/audit.log" template="fworch")
      if $programname startswith '{{ product_name }}' and $msg contains "FWORCHAlert" then action(type="omfile" file="/var/log/{{ product_name }}/alert.log" template="fworch")
      if $programname == '{{ product_name }}-webhook' then action(type="omfile" file="/var/log/{{ product_name }}/webhook.log" template="fworch")
  become: yes

- name: edit logrotate
  blockinfile:
    path: "/etc/logrotate.d/{{ product_name }}"
    create: yes
    block: |
      /var/log/{{ product_name }}/*.log {
          compress
          maxage 7
          rotate 99
          size=+4096k
          missingok
          copytruncate
          sharedscripts
              prerotate
                      systemctl stop {{ product_name }}-importer-legacy.service >/dev/null 2>&1
              endscript
              postrotate
                      systemctl start {{ product_name }}-importer-legacy.service >/dev/null 2>&1
              endscript
      }
  become: yes

- name: reload rsyslog service
  service:
    name: "rsyslog"
    state: restarted
  become: yes
