- block: 
     - name: remove complete {{ base_dir }} dir 
       file:
          state: absent
          path: "{{ {{ base_dir }} }}"

     - name: update operating system packages .deb based
       apt:
         upgrade: dist
       when: ansible_facts['distribution'] == "Ubuntu" or ansible_facts['distribution'] == "Debian"

     - name: update operating system packages .rpm based (untested)
       apt:
         upgrade: dist
       when: ansible_facts['distribution'] == "Red Hat" or ansible_facts['distribution'] == "CentOS"

     - name: install package rsyslog
       package:
        name: "rsyslog"
        state: present

     - name: create log dir for {{ product_name }} on ubuntu - owner syslog
       file:
         path: "/var/log/{{ product_name }}/"
         state: directory
         owner: syslog
         group: syslog
         mode: 0775
       when: ansible_facts['distribution'] == "Ubuntu"
         
     - name: create log dir for {{ product_name }} on debian - owner root
       file:
         path: "/var/log/{{ product_name }}/"
         state: directory
         owner: root
         group: root
         mode: 0775
       when: ansible_facts['distribution'] == "Debian"
         
     - name: edit rsyslog
       blockinfile:
         path: "/etc/rsyslog.d/30-{{ product_name }}.conf"
         create: yes
         block: |
             # syslog for ITSecOrg
             # Log ITSecOrg log messages to file
             :msg,contains,"ITSecOrg" /var/log/itsecorg.log
             local6.warning                 /var/log/{{ product_name }}/{{ product_name }}.error
             local6.notice                  /var/log/{{ product_name }}/{{ product_name }}.log
             local6.=info                   /var/log/{{ product_name }}/{{ product_name }}.login
             local6.debug                   /var/log/{{ product_name }}/{{ product_name }}.debug

     - name: edit logrotate
       blockinfile:
         path: "/etc/logrotate.d/{{ product_name }}.conf"
         create: yes
         block: |
            /var/log/{{ product_name }}/{{ product_name }}.log /var/log/{{ product_name }}/{{ product_name }}.debug /var/log/{{ product_name }}/{{ product_name }}.error /var/log/{{ product_name }}/{{ product_name }}.login {
               compress
               maxage 7
               rotate 99
               size=+4096k
               missingok
               copytruncate
               sharedscripts
                   prerotate
                           /etc/init.d/itsecorg-import stop >/dev/null
                   endscript
                   postrotate
                           /etc/init.d/itsecorg-import start >/dev/null
                   endscript
            }

     - name: reload rsyslog service
       service:
        name: "rsyslog"
        state: restarted

     - name: create group itsecorg
       group:
        name: itsecorg
        gid: "{{ user_id }}"
        state: present
       
     - name: add user {{ iso_user }}
       user:
        name: "{{ iso_user }}"
        comment: "{{ product_name }} User"
        uid: "{{ user_id }}"
        home: "{{ iso_home }}"
        shell: /bin/bash
        group: itsecorg
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa

     - name: create etc dir
       file:
         path: "{{ iso_home }}/etc"
         state: directory
         owner: "{{ iso_user }}"
         group: "{{ iso_user }}"

     - name: copy iso.conf to target
       copy:
        src: iso.conf
        dest: "{{ iso_home }}/etc/iso.conf"
        owner: "{{ iso_user }}"
        group: "{{ iso_user }}"
        
  become: yes
  
