# this playbook sets up a connection to cactus test firewall sting
- block:
    - set_fact: importer_hostname="{{ ansible_hostname }}"          #  this only works for importer = backend

    - name: create .pgpass file
      lineinfile:
        path: "{{ fworch_home }}/.pgpass"
        create: yes
        mode: 0600
        line: "{{ fworch_db_host }}:{{ fworch_db_port }}:{{ fworch_db_name }}:{{ fworch_dbadmin_name }}:{{ dbadmin_pwd }}"

    - name: insert sting-mgmt
      shell: 'psql -h {{ fworch_db_host }} -U {{ fworch_dbadmin_name }} -d {{ fworch_db_name }} -c "DO \$do\$ BEGIN IF NOT EXISTS (SELECT * FROM management WHERE mgm_id=3) THEN insert into management (mgm_id,dev_typ_id,mgm_name,ssh_private_key,ssh_public_key,ssh_hostname,ssh_port,ssh_user,do_not_import,config_path,importer_hostname) VALUES (3,9,''sting-mgmt'',''{{ dbadmin_pwd }}'','''',''{{ sting_ip }}'',''{{ sting_port }}'',''{{ fworch_user }}'',false, '''',''{{ importer_hostname }}'');  END IF; END \$do\$"'

    - name: insert sting-gw
      shell: 'psql -h {{ fworch_db_host }} -U {{ fworch_dbadmin_name }} -d {{ fworch_db_name }} -c "DO \$do\$ BEGIN IF NOT EXISTS (SELECT * FROM device WHERE dev_id=3) THEN insert into device (dev_id,mgm_id,dev_name,dev_rulebase,dev_typ_id) VALUES (3,3,''sting-gateway'',''cactus_Security_neu'',9); END IF; END \$do\$"'

    - name: clean up .pgpass file
      file:
        path: "{{ fworch_home }}/.pgpass"
        state: absent

  become: yes
  become_user: itsecorg
