- block:
    - name: Install importer perl modules 
      package: name={{ item }} state=present
      with_items:
        - libdbi-perl 
        - libdbd-pg-perl 
        - libdate-calc-perl 
        - psmisc 
        - libnet-cidr-perl 
        - libsys-syslog-perl 
        - libexpect-perl
        - libcgi-pm-perl

    - name: copy importer files
      copy:
        src: "importer"
        dest: "{{ fworch_home }}"
        owner: "{{ fworch_user }}"
        group: "{{ fworch_user }}"
        mode: 0755

#    - name: set x-flag for importer executables
#      file:
#        path: "{{ fworch_home }}/importer/*"
#        state: file
#        mode: 0755

    - name: copy importer bin
      copy:
        src: "bin/"
        dest: "{{ fworch_home }}/bin/"
        mode: 0755
        owner: "{{ fworch_user }}"
        group: "{{ fworch_user }}"

    - name: copy import.conf
      copy:
        src: "import.conf"
        dest: "{{ fworch_home }}/etc/import.conf"
        mode: 0755
        owner: "{{ fworch_user }}"
        group: "{{ fworch_user }}"

    - name: copy importer rc script
      copy:
        src: "import_{{ product_name }}-main-rc"
        dest: "/etc/init.d/{{ product_name }}-importer"
        mode: 0755
        owner: root
        group: root

    - name: create links in rcx.d dirs
      command: "/usr/sbin/update-rc.d {{ product_name }}-importer defaults"

    - name: start {{ product_name }} importer 
      shell: "/etc/init.d/{{ product_name }}-importer start"
  become: yes
      