- block:
    - name: Install importer perl modules 
      package: name={{ item }} state=present
      loop:
        - libdbi-perl 
        - libdbd-pg-perl 
        - libdate-calc-perl 
        - psmisc 
        - libnet-cidr-perl 
        - libsys-syslog-perl 
        - libexpect-perl
        - libcgi-pm-perl

    - name: copy importer files
      copy:
        src: "importer"
        dest: "{{ fworch_home }}"
        owner: "{{ fworch_user }}"
        group: "{{ fworch_user }}"
        mode: "0755"

    - name: set x-flag for importer executables (top level only)
      file:
        path: "{{ item }}"
        state: file
        mode: "0755"
      with_fileglob: "{{ fworch_home }}/importer/*"

    - name: copy import.conf
      copy:
        src: "import.conf"
        dest: "{{ fworch_home }}/etc/import.conf"
        mode: "0755"
        owner: "{{ fworch_user }}"
        group: "{{ fworch_user }}"

    - name: copy importer rc script
      copy:
        src: "import-main-rc"
        dest: "/etc/init.d/{{ product_name }}-importer"
        mode: "0755"
        owner: root
        group: root

    - name: create links in rcx.d dirs
      command: "/usr/sbin/update-rc.d {{ product_name }}-importer defaults"

    - name: start {{ product_name }} importer 
      command: "/etc/init.d/{{ product_name }}-importer start"

    # todo: the following did not work at first try, so sticking to /etc/init.d for now:

    # - name: copy importer systemd service script
    #   template:
    #     src: "{{ product_name }}-importer.service.j2"
    #     dest: "/lib/systemd/system/{{ product_name }}-importer.service"
    #     backup: yes
    #     mode: "0644"
    #     owner: "root"
    #   become: yes

    # - name: make importer run at host startup
    #   command: "systemctl enable {{ product_name }}-importer"
    #   become: yes

    # - name: start importer
    #   command: "systemctl start {{ product_name }}-importer"
    #   become: yes

  become: yes
