

- name: set importer user password randomly
  set_fact:
    importer_password: "{{ random_generated_pw }}"
  when: (testkeys is not defined or not testkeys|bool)

- name: write importer_password to secrets directory
  copy:
    content: "{{ importer_password }}"
    dest: "{{ importer_password_file }}"
    mode: '0600'
    owner: "{{ fworch_user }}"
    group: "{{ fworch_group }}"
  become: yes

- name: Set importer password in ldap
  ldap_passwd:
    dn: uid=importer,ou=tenant0,ou=operator,ou=user,{{ openldap_path }}
    passwd: "{{ importer_password }}"
    server_uri: "{{ openldap_url }}"
    bind_dn: "{{ openldap_superuser_dn }}"
    bind_pw: "{{ ldap_manager_pwd }}"
