
### general settings
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
product_name: fworch

### operating system settings
user_id: 60320
fworch_user: "{{ product_name }}"
fworch_parent_dir: "/usr/local"
fworch_home: "{{ fworch_parent_dir }}/{{ product_name }}"
http_proxy: ""
#http_proxy: http://admsrv.int.cactus:3128
https_proxy: "{{ http_proxy }}"
proxy_exceptions: ""
proxy_env:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ https_proxy }}"
        validate_certs: false

### database
fworch_db_port: 5432
# fworch_db_host: 10.1.1.83
fworch_db_host: 127.0.0.1
fworch_db_name: fworchdb
fworch_dbadmin_name: dbadmin
api_service_name: hasura-docker-api

### dotnet
dotnet_deb_name: "packages-microsoft-prod.deb"
dotnet_version: "3.1"
dotnet_mode: "Debug"
# dotnet_mode: "Release"

### logging
syslog_proto: tcp
syslog_host: 127.0.0.1
syslog_port: 514
auth_server_syslog_id: "{{ product_name }}.auth-server"
ui_syslog_id: "{{ product_name }}-ui"
ldap_syslog_id: slapd

### apache: both package and dir name (needed both on ui and api hosts):
web_server_name: apache2
http_conf_dir: /etc/{{ web_server_name }}/sites-available/

### to be moved: passwords
dbadmin_pwd: "st8chel"
fworch_pwd: "st8chel"
admin_pwd: "fworch.1"
