# database_dir: /var/lib/pgsql/data
postgresql_package: postgresql
postgresql_test_package: pgtap
postgresql_c_client_library_header_files: libpq-dev
postgresql_dev_package_prefix: postgresql-server-dev
database_install_dir: "{{ fworch_home }}/database"

# table_space variable can be used to create database in another place where there is enough space
# table_space: /var/db/fworch_tablespace
# table_space_name: fworch

database_users:
  - dbbackup
  - fworchimporter
  - textreader
  # COMMENT ON ROLE textreader IS 'only used for reading from text_msg';

database_groups:
  - secuadmins
  - dbbackupusers
  - configimporters
  - reporters
  - fworchadmins
