
# web_server_name: "apache2" 
# http_conf_dir: /etc/{{ web_server_name }}/sites-available/
ui_port: 5000
ui_web_port: 443
ui_app_name: "{{ product_name }}"
ui_dir: "{{ fworch_home }}/ui/files"
ui_start_dir: "{{ ui_dir }}/FWO_UI"

# correct name for demo installation:
ui_server_name: demo.itsecorg.de

ui_server_admin: root@localhost
ui_hostname: "localhost"
ui_php_dir: "{{ fworch_home }}/web/htdocs"
ui_php_web_port: 8443
ui_service_name: "{{ product_name }}-ui"
