
sample_config_user: fworchsample
sample_config_user_home: "/home/{{ sample_config_user }}"
sample_data_rate: medium
sample_role_purpose: demo
sample_fortigate_name: fortigate_demo
sample_checkpoint_name: "dummy only relevant for testing"
demo_cpr8x_name: "CPR81_demo"
demo_cpr8x_uri: "https://fwodemodata.cactus.de/demo09_cpr81.json"
demo_fos_name: "FortiOS_demo"
demo_fos_uri: "https://fwodemodata.cactus.de/demo10_fOS.json"
sample_postfix: _demo

# sample openldap server
second_ldap_db: no
sample_ldap_path: "dc=example,dc=com"
sample_ldap_domain_name: example.com
sample_ldap_superuser_name: "cn=Manager,ou=user,{{ sample_ldap_path }}"
