
name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# test change

on:
  push:
    branches: [ main,develop ]
    paths-ignore:
    - 'documentation/**'
    - 'design/**'

  pull_request:
    types: [ ready_for_review review_requested ]
    branches: [ main,develop ]
    paths-ignore:
    - 'documentation/**'
    - 'design/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: test build on merge
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: do test install in case of merged pull request
      run: cd /home/runner/work/firewall-orchestrator/firewall-orchestrator && ansible-playbook -e 'run_on_github=yes testkeys=yes' --skip-tags test site.yml -K

  review:
    name: Review code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: do test install in case of reviewable PR
      run: cd /home/runner/work/firewall-orchestrator/firewall-orchestrator && ansible-playbook -e 'run_on_github=yes testkeys=yes' --skip-tags test site.yml -K
